/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-112686-g3f890fbfd9-20231104"
#endif /* AVUTIL_FFVERSION_H */
