/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-106936-gdd99d34d67-20220519"
#endif /* AVUTIL_FFVERSION_H */
