/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-113658-gacacf8a313-20240216"
#endif /* AVUTIL_FFVERSION_H */
