######################################################################
# Automatically generated by qmake (3.1) Fri Apr 15 21:28:40 2022
######################################################################

TEMPLATE = app
TARGET = VideoPlayer
INCLUDEPATH += .

# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += about.h \
           audio_play.h \
           decode_thread.h \
           ffmpeg_decode.h \
           mainwindow.h \
           ui_about.h \
           ui_mainwindow.h \
           "Visual Leak Detector/include/vld.h" \
           "Visual Leak Detector/include/vld_def.h" \
           ffmpeg/include/libavcodec/ac3_parser.h \
           ffmpeg/include/libavcodec/adts_parser.h \
           ffmpeg/include/libavcodec/avcodec.h \
           ffmpeg/include/libavcodec/avdct.h \
           ffmpeg/include/libavcodec/avfft.h \
           ffmpeg/include/libavcodec/bsf.h \
           ffmpeg/include/libavcodec/codec.h \
           ffmpeg/include/libavcodec/codec_desc.h \
           ffmpeg/include/libavcodec/codec_id.h \
           ffmpeg/include/libavcodec/codec_par.h \
           ffmpeg/include/libavcodec/d3d11va.h \
           ffmpeg/include/libavcodec/defs.h \
           ffmpeg/include/libavcodec/dirac.h \
           ffmpeg/include/libavcodec/dv_profile.h \
           ffmpeg/include/libavcodec/dxva2.h \
           ffmpeg/include/libavcodec/jni.h \
           ffmpeg/include/libavcodec/mediacodec.h \
           ffmpeg/include/libavcodec/packet.h \
           ffmpeg/include/libavcodec/qsv.h \
           ffmpeg/include/libavcodec/vdpau.h \
           ffmpeg/include/libavcodec/version.h \
           ffmpeg/include/libavcodec/version_major.h \
           ffmpeg/include/libavcodec/videotoolbox.h \
           ffmpeg/include/libavcodec/vorbis_parser.h \
           ffmpeg/include/libavcodec/xvmc.h \
           ffmpeg/include/libavdevice/avdevice.h \
           ffmpeg/include/libavdevice/version.h \
           ffmpeg/include/libavdevice/version_major.h \
           ffmpeg/include/libavfilter/avfilter.h \
           ffmpeg/include/libavfilter/buffersink.h \
           ffmpeg/include/libavfilter/buffersrc.h \
           ffmpeg/include/libavfilter/version.h \
           ffmpeg/include/libavfilter/version_major.h \
           ffmpeg/include/libavformat/avformat.h \
           ffmpeg/include/libavformat/avio.h \
           ffmpeg/include/libavformat/version.h \
           ffmpeg/include/libavformat/version_major.h \
           ffmpeg/include/libavutil/adler32.h \
           ffmpeg/include/libavutil/aes.h \
           ffmpeg/include/libavutil/aes_ctr.h \
           ffmpeg/include/libavutil/attributes.h \
           ffmpeg/include/libavutil/audio_fifo.h \
           ffmpeg/include/libavutil/avassert.h \
           ffmpeg/include/libavutil/avconfig.h \
           ffmpeg/include/libavutil/avstring.h \
           ffmpeg/include/libavutil/avutil.h \
           ffmpeg/include/libavutil/base64.h \
           ffmpeg/include/libavutil/blowfish.h \
           ffmpeg/include/libavutil/bprint.h \
           ffmpeg/include/libavutil/bswap.h \
           ffmpeg/include/libavutil/buffer.h \
           ffmpeg/include/libavutil/camellia.h \
           ffmpeg/include/libavutil/cast5.h \
           ffmpeg/include/libavutil/channel_layout.h \
           ffmpeg/include/libavutil/common.h \
           ffmpeg/include/libavutil/cpu.h \
           ffmpeg/include/libavutil/crc.h \
           ffmpeg/include/libavutil/des.h \
           ffmpeg/include/libavutil/detection_bbox.h \
           ffmpeg/include/libavutil/dict.h \
           ffmpeg/include/libavutil/display.h \
           ffmpeg/include/libavutil/dovi_meta.h \
           ffmpeg/include/libavutil/downmix_info.h \
           ffmpeg/include/libavutil/encryption_info.h \
           ffmpeg/include/libavutil/error.h \
           ffmpeg/include/libavutil/eval.h \
           ffmpeg/include/libavutil/ffversion.h \
           ffmpeg/include/libavutil/fifo.h \
           ffmpeg/include/libavutil/file.h \
           ffmpeg/include/libavutil/film_grain_params.h \
           ffmpeg/include/libavutil/frame.h \
           ffmpeg/include/libavutil/hash.h \
           ffmpeg/include/libavutil/hdr_dynamic_metadata.h \
           ffmpeg/include/libavutil/hdr_dynamic_vivid_metadata.h \
           ffmpeg/include/libavutil/hmac.h \
           ffmpeg/include/libavutil/hwcontext.h \
           ffmpeg/include/libavutil/hwcontext_cuda.h \
           ffmpeg/include/libavutil/hwcontext_d3d11va.h \
           ffmpeg/include/libavutil/hwcontext_drm.h \
           ffmpeg/include/libavutil/hwcontext_dxva2.h \
           ffmpeg/include/libavutil/hwcontext_mediacodec.h \
           ffmpeg/include/libavutil/hwcontext_opencl.h \
           ffmpeg/include/libavutil/hwcontext_qsv.h \
           ffmpeg/include/libavutil/hwcontext_vaapi.h \
           ffmpeg/include/libavutil/hwcontext_vdpau.h \
           ffmpeg/include/libavutil/hwcontext_videotoolbox.h \
           ffmpeg/include/libavutil/hwcontext_vulkan.h \
           ffmpeg/include/libavutil/imgutils.h \
           ffmpeg/include/libavutil/intfloat.h \
           ffmpeg/include/libavutil/intreadwrite.h \
           ffmpeg/include/libavutil/lfg.h \
           ffmpeg/include/libavutil/log.h \
           ffmpeg/include/libavutil/lzo.h \
           ffmpeg/include/libavutil/macros.h \
           ffmpeg/include/libavutil/mastering_display_metadata.h \
           ffmpeg/include/libavutil/mathematics.h \
           ffmpeg/include/libavutil/md5.h \
           ffmpeg/include/libavutil/mem.h \
           ffmpeg/include/libavutil/motion_vector.h \
           ffmpeg/include/libavutil/murmur3.h \
           ffmpeg/include/libavutil/opt.h \
           ffmpeg/include/libavutil/parseutils.h \
           ffmpeg/include/libavutil/pixdesc.h \
           ffmpeg/include/libavutil/pixelutils.h \
           ffmpeg/include/libavutil/pixfmt.h \
           ffmpeg/include/libavutil/random_seed.h \
           ffmpeg/include/libavutil/rational.h \
           ffmpeg/include/libavutil/rc4.h \
           ffmpeg/include/libavutil/replaygain.h \
           ffmpeg/include/libavutil/ripemd.h \
           ffmpeg/include/libavutil/samplefmt.h \
           ffmpeg/include/libavutil/sha.h \
           ffmpeg/include/libavutil/sha512.h \
           ffmpeg/include/libavutil/spherical.h \
           ffmpeg/include/libavutil/stereo3d.h \
           ffmpeg/include/libavutil/tea.h \
           ffmpeg/include/libavutil/threadmessage.h \
           ffmpeg/include/libavutil/time.h \
           ffmpeg/include/libavutil/timecode.h \
           ffmpeg/include/libavutil/timestamp.h \
           ffmpeg/include/libavutil/tree.h \
           ffmpeg/include/libavutil/twofish.h \
           ffmpeg/include/libavutil/tx.h \
           ffmpeg/include/libavutil/version.h \
           ffmpeg/include/libavutil/video_enc_params.h \
           ffmpeg/include/libavutil/xtea.h \
           ffmpeg/include/libswresample/swresample.h \
           ffmpeg/include/libswresample/version.h \
           ffmpeg/include/libswresample/version_major.h \
           ffmpeg/include/libswscale/swscale.h \
           ffmpeg/include/libswscale/version.h \
           ffmpeg/include/libswscale/version_major.h \
           "/Visual Leak Detector/include/vld.h"
FORMS += about.ui mainwindow.ui
SOURCES += about.cpp \
           audio_play.cpp \
           decode_thread.cpp \
           ffmpeg_decode.cpp \
           main.cpp \
           mainwindow.cpp \
           debug/qrc_qmake_qmake_qm_files.cpp \
           release/qrc_qmake_qmake_qm_files.cpp \
           ffmpeg/share/ffmpeg/examples/avio_list_dir.c \
           ffmpeg/share/ffmpeg/examples/avio_reading.c \
           ffmpeg/share/ffmpeg/examples/decode_audio.c \
           ffmpeg/share/ffmpeg/examples/decode_video.c \
           ffmpeg/share/ffmpeg/examples/demuxing_decoding.c \
           ffmpeg/share/ffmpeg/examples/encode_audio.c \
           ffmpeg/share/ffmpeg/examples/encode_video.c \
           ffmpeg/share/ffmpeg/examples/extract_mvs.c \
           ffmpeg/share/ffmpeg/examples/filter_audio.c \
           ffmpeg/share/ffmpeg/examples/filtering_audio.c \
           ffmpeg/share/ffmpeg/examples/filtering_video.c \
           ffmpeg/share/ffmpeg/examples/http_multiclient.c \
           ffmpeg/share/ffmpeg/examples/hw_decode.c \
           ffmpeg/share/ffmpeg/examples/metadata.c \
           ffmpeg/share/ffmpeg/examples/muxing.c \
           ffmpeg/share/ffmpeg/examples/qsvdec.c \
           ffmpeg/share/ffmpeg/examples/remuxing.c \
           ffmpeg/share/ffmpeg/examples/resampling_audio.c \
           ffmpeg/share/ffmpeg/examples/scaling_video.c \
           ffmpeg/share/ffmpeg/examples/transcode_aac.c \
           ffmpeg/share/ffmpeg/examples/transcoding.c \
           ffmpeg/share/ffmpeg/examples/vaapi_encode.c \
           ffmpeg/share/ffmpeg/examples/vaapi_transcode.c
RESOURCES += debug/qmake_qmake_qm_files.qrc
TRANSLATIONS += VideoPlayer_en_001.ts
